### ISSUE TITLE
Habemus website

### ISSUE THREAD

**Issue by OtacilioN** [ReciHub/Hub-de-Comunidades#3]
É com grande felicidade que o anuncio que o repositório está configurado para GitHub Pages com o Jekyll, o tema escolhido foi o Architect.

As mudanças no site podem ser feitas diretamente através do [README.md dentro de docs](https://github.com/ReciHub/Hub-de-Comunidades/blob/master/docs/README.md), em poucos segundos o site é atualizado após um commit. 

E aqui vai o link do nosso site: https://recihub.github.io/Hub-de-Comunidades/

**Comment by Rodrigusto** [comment]
Cara! Vocês estão muito de Parabéns! {{APLAUSOS}}

**Comment by OtacilioN** [comment]
Opa @Rodrigusto valeu! Bem vindo ao nosso ecossitema, sinta-se a vontade em colaborar nos nossos projetos, e qualquer dúvida pode contar conosco!
